import './globals.css'
import { Maven_Pro } from 'next/font/google'
import { Toaster } from '@/ui/toasts/toaster'
import { cn } from '@/lib/utils'
import { SiteHeader } from '@/modules/navigation/site-header'

const font = Maven_Pro({ subsets: ['latin'], variable: '--font' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: { icon: './favicon.ico' },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn('font-sans antialiased', font.variable)}>
      <body className="min-h-screen dark:bg-slate-900 dark:text-slate-100">
        <SiteHeader />
        {children}
        <Toaster />
      </body>
    </html>
  )
}
