import './globals.css'
import localFont from 'next/font/local'

const font = localFont({ src: './BagnardSans.otf', variable: '--font' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: { icon: './favicon.ico' },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={font.variable}>
      <body>{children}</body>
    </html>
  )
}
